core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name = "index"),
    path("category/<int:id>", views.get_category, name = "category"),
    path("language/<str:lang>", views.select_language_document, name = "langPage")
]

documents/urls.py
from django.urls import path 
from . import views

app_name = "documents"

urlpatterns = [
    path("<int:id>", views.view_document, name = "viewDocument"),
    path("form/", views.add_document_view, name = "addDocument"),
    path("edit/<int:id>", views.edit_document_view, name = "editView"),
    path("pdf/<int:id>", views.generate_pdf, name = "pdf")
]

legal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="My API description",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="Awesome License"),
    ),
    public=True,
    permission_classes=[permissions.IsAuthenticated],
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('documents/', include("documents.urls")),
    path('', include("core.urls")),
    path('authentication/', include("accounts.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("django_prometheus.urls")),
    path('search/', include('search.urls')),
    path('api/', include('documents_api.urls')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    #go to /metrics/ url for logs
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = "search"

urlpatterns = [
    path("", views.search_view, name = "search")
]

core/views.py
from django.shortcuts import render
from django.core.cache import cache
from django.conf import settings
from documents.models import Category, Document, Language

CACHE_TTL = getattr(settings, "CACHE_TTL")

def index(request):
    cached_documents = cache.get("cached_documents")
    cached_categories = cache.get("cached_categories")

    if cached_documents is None or cached_categories is None:
        try:
            all_categories = Category.objects.all()
            documents = Document.objects.all()

            cache.set('cached_documents', documents, CACHE_TTL)
            cache.set('cached_categories', all_categories, CACHE_TTL)
        except Exception as e:
            print("Error fetching data from the database:", e)
            # Handle the error appropriately, e.g., return an error response

    else:
        print("Data found in cache.")

        all_categories = cached_categories
        documents = cached_documents
    print(Language.objects.all())
    context = {"allCategories": all_categories, "documents": documents, "languages":Language.objects.all()}
    return render(request, "core/index.html", context)


def get_category(request, id):
    cached_category = cache.get("cached_category")
    cached_categories = cache.get("cached_categories")
    cached_documents = cache.get("cached_documents")

    if cached_documents is None or cached_categories is None or cached_category is None:

        all_categories = Category.objects.all()
        category = Category.objects.get(pk = id)
        documents = Document.objects.filter(category = category)
        
        cache.set("cached_category", category, CACHE_TTL)
        cache.set("cached_categories", all_categories, CACHE_TTL)
        cache.set("cached_documents", documents, CACHE_TTL)
    else:
        all_categories = cached_categories
        category = cached_category
        documents = cached_documents

    context = {"allCategories":all_categories,"category":category, "documents":documents}
    return render(request,"core/index.html", context)   

def select_language_document(request, lang):
    language = Language.objects.get(language_name = lang)
    documents =  Document.objects.filter(language = language)
    categories = Category.objects.filter(language = language)
    context = {"allCategories":categories,"documents":documents, "languages":Language.objects.all()}
    return render(request, "core/index.html", context)

core/templates/core/index.html
{% extends "core/layout.html" %}

{% block body %}

<h2>{{category.title}} Documents</h2>
    <h2>Languages</h2>
        <ul class="list-group">
            <li class="list-group-item"><a href="{% url "core:index" %}">All</a></li>   

        {% for language in languages %}
            <li class="list-group-item"><a href="{% url "core:langPage" language.language_name%}">{{language}}</a></li>   
        {% endfor %}
        </ul>
    
    


<ul class="list-group">
    {% for document in documents %}
    <li class="list-group-item d-flex gap-3 align-items-center">
        <a href="{% url "documents:viewDocument" document.id %}" class="text-decoration-none">{{document.header}}</a>
        <p class="mb-0 flex-grow-1"></p>
    </li>
    {% endfor %} 
</ul>
{% if request.user.is_authenticated %}
<a href="{% url "documents:addDocument" %}">
    <button class = "btn btn-success" data-toggle = "modal" data-target = "#exampleModal">Add</button>
</a>
{% endif %}


{% endblock body %}
              

core/templates/core/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Website Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
   </head>
<body>
    <header class="p-3 mb-2 bg-light border-bottom">
        <div class="container-fluid d-flex flex-wrap align-items-center justify-content-center justify-content-md-between">
            <a href="{% url "core:index" %}" class="text-dark text-decoration-none fs-4">
                <h1>Gozle Legal</h1>
            </a>
            
            <form action="{% url "search:search" %}" method="get" class="d-flex">
                <input type="text" name="q" placeholder="Search documents..." class="form-control me-2">
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
        </div>
    </header>

    <main class="container mt-5">
        <div class="row gy-5">
            <aside class="col-md-3">
                <h2>Categories</h2>
                <ul class="list-group">
                    {% for category in allCategories %}
                    <li class="list-group-item"><a href="{% url "core:category" category.id%}">{{category.title}}</a></li>   
                    {% endfor %}
                </ul>
            </aside>

            <section class="col-md-9">
                {% block body %}

                {% endblock body %}
                
            </section>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% block scripts %}


{% endblock scripts %}
</body>
</html>

core/templates/core/view-document.html
{% extends "core/layout.html" %}
{% load static %}
{% block body %}
<article class="mb-4">
    <h1><div id = "doc-id">{{document.id}}</div> {{document.header}}</h1>
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            {% comment %} <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>
                <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>
                <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>
                <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>
                <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>
                <h2 class="section-heading">The Final Frontier</h2>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.</p>
                <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far too little for the next ten.</blockquote>
                <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development.</p>
                <h2 class="section-heading">Reaching for the Stars</h2>
                <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man.</p>
                <a href="#!"><img class="img-fluid" src="assets/img/post-sample-image.jpg" alt="..." /></a>
                <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before.</p>
                <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                <p>
                    Placeholder text by
                    <a href="http://spaceipsum.com/">Space Ipsum</a>
                    &middot; Images by
                    <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                </p>
            </div> {% endcomment %}
            <div class="row gx-4 gx-lg-5 justify-content-center">
                {{document.body|safe}}
                <a href="{% url "documents:pdf" document.id%}"  ><button id="download-pdf-btn" class="btn btn-primary">Download PDF</button></a>
            </div>
        </div>
    </div>
</article>
{% if request.user.is_authenticated %}
<a href="{% url "documents:editView" document.id %}"><button class="btn btn-info">Edit</button></a>
<button class="btn btn-danger" data-toggle = "modal" data-target = "#deleteModal">Delete</button>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Deleting Document</h5>
          <button type="button" class="close btn btn-white" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">X</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this Document? {{document.header}}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal" id = "delete-document">Delete</button>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
{% endblock body %}

{% block scripts %}

    <!-- Include CKEditor JS files -->
    <script src="https://cdn.ckeditor.com/ckeditor5/37.0.0/classic/ckeditor.js"></script>
    <script src = "{% static "core/js/index.js" %}"></script>
{% endblock scripts %}




